\documentclass[12pt]{article}

\input{4mbapreamble}
\input{4mba2q}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% FANCY HEADER AND FOOTER STUFF %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\usepackage{fancyhdr,lastpage}
\pagestyle{fancy}
\fancyhf{} % clear all header and footer parameters
%%%\lhead{Student Name: \theblank{4cm}}
%%%\chead{}
%%%\rhead{Student Number: \theblank{3cm}}
%%%\lfoot{\small\bfseries\ifnum\thepage<\pageref{LastPage}{CONTINUED\\on next page}\else{LAST PAGE}\fi}
\lfoot{}
\cfoot{{\small\bfseries Page \thepage\ of \pageref{LastPage}}}
\rfoot{}
\renewcommand\headrulewidth{0pt} % Removes funny header line
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{document}
\SweaveOpts{concordance=TRUE}

\begin{center}
{\bf Mathematics 4MB3/6MB3 Mathematical Biology\\
\smallskip
2018 ASSIGNMENT 2}\\
\medskip
\underline{\emph{Group Name}}: \texttt{{\color{blue} $\pi$rates}}\\
\medskip
\underline{\emph{Group Members}}: {\color{blue} Megan Hartwell, Ahmad Mahmood, Bradley Montgomery, Courtney Mulholland}
\end{center}

\bigskip
\noindent
This assignment is due in class on \textcolor{red}{\bf Monday 5 February 2018 at 11:30am}.

\section{Plot P\&I mortality in Philadelphia in 1918}

\begin{enumerate}[(a)]

\item \PhilaDataReceived

\item \PhilaDataReadA
<<read.phila.data>>=
datafile <- "pim_us_phila_city_1918_dy.csv"
philadata <- read.csv(datafile)
philadata$date <- as.Date(philadata$date)
@ 
\PhilaDataReadB

\item \PhilaDataReproduceA

  {\color{blue}
<<Q1, eval=TRUE, fig=TRUE, fig.show="hold", width = 6, height = 4>>=

plot(philadata, pch=21, col="grey", type="l",bty="L",
     ann=FALSE,las=1,xaxs="i") ## Plot underlying grey line
points(philadata, pch=21, bg="red",cex=0.65,lwd=0.45) ## Add red pts
## Add blue labels
mtext("Date", side=1, adj=1, line=1.5, font=1, cex=1.5, col='blue')  
mtext("P&I Deaths", side=2, padj=-7.0, line=-3.2, font=1, 
      las=1, cex=1.5, col='blue')
@
  }

\PhilaDataReproduceB

\end{enumerate}

\section{Estimate $\R_0$ from the Philadelphia P\&I time series}

\begin{enumerate}[(a)]

\item \EstimateRna

 {\color{blue} \begin{proof}[Solution]
 {\color{magenta}\dots beautifully clear and concise text to be inserted here\dots}
 \end{proof}
 }

\item \EstimateRnb

  {\color{blue} \begin{proof}[Solution]
  {\color{magenta}\dots beautifully clear text and plot(s) here \dots\ interspersed with \Rlogo code if this is a \texttt{knitr} script}
  \end{proof}
  }
  
\item \EstimateRnc

  {\color{blue} \begin{proof}[Solution]
  {\color{magenta}\dots beautifully clear text here \dots\ including some embedded \Rlogo code to estimate $\R_0$ if this is a \texttt{knitr} script}
  \end{proof}
  }

\end{enumerate}

\section{Fit the basic SIR model to the Philadelphia P\&I time series}

\begin{enumerate}[(a)]

\item \FitSIRa

\item \FitSIRbIntro
\begin{itemize}
    \item Your code will first need to load the \code{deSolve} package:
<<load.deSolve,message=FALSE>>=
library("deSolve")
@       
    \item \FitSIRbii
<<plot.sine,fig.height=4>>=
plot.sine <- function( xmin=0, xmax=2*pi ) {
  x <- seq(xmin,xmax,length=100)
  plot(x, sin(x), typ="l")
  grid() # add a light grey grid
}
plot.sine(xmax=4*pi)
@ 
  \item \FitSIRbiiiA
<<SI.vec.fld>>=
## Vector Field for SI model
SI.vector.field <- function(t, vars, parms=c(beta=2,gamma=1)) {
  with(as.list(c(parms, vars)), {
    dx <- -beta*x*y # dS/dt
    dy <- beta*x*y  # dI/dt
    vec.fld <- c(dx=dx, dy=dy)
    return(list(vec.fld)) # ode() requires a list
  })
}
@ 

\FitSIRbiiiB
<<draw.soln,tidy=FALSE>>=
## Draw solution
draw.soln <- function(ic=c(x=1,y=0), tmax=1, 
                      times=seq(0,tmax,by=tmax/500), 
                      func, parms, ... ) {
  soln <- ode(ic, times, func, parms)
  lines(times, soln[,"y"], col="blue", lwd=3, ... )
}
@ 
\FitSIRbiiiC
<<eval=FALSE>>=
  soln <- ode(times=times, func=func, parms=parms, y=ic)
@ 

We can now use our \code{draw.soln()} function to plot a few solutions of the SI model.

<<plot.SI.model,tidy=FALSE,fig.height=3.5,fig.width=6>>=
## Plot solutions of the SI model
tmax <- 10 # end time for numerical integration of the ODE
## draw box for plot:
plot(0,0,xlim=c(0,tmax),ylim=c(0,1),
     type="n",xlab="Time (t)",ylab="Prevalence (I)",las=1)
## initial conditions:
I0 <- 0.001
S0 <- 1 - I0
## draw solutions for several values of parameter beta:
betavals <- c(1.5,2,2.5)
for (i in 1:length(betavals)) {
  draw.soln(ic=c(x=S0,y=I0), tmax=tmax,
            func=SI.vector.field,
            parms=c(beta=betavals[i],gamma=1),
            lty=i # use a different line style for each solution
            )
}
@ 


  \end{itemize}
 
 {\color{blue} \begin{proof}[Solution]
 \begin{itemize}
 \smallskip
 \item We first wrote the following code to represent the ODE as a vector field that \Rlogo can integrate numerically. We've chosen to use the parameters $\gamma$ and $\beta$.
<<Q3b1>>=
SIR.vector.field <- function(t, vars, parms=c(beta=2,gamma=1)) {
  # Writes vector field of these differential equations
  with(as.list(c(parms, vars)), {
    dS <- -1*beta*S*I # dS/dt
    dI <- beta*S*I-gamma*I  # dI/dt
    dR <- gamma*I  # dR/dt
    vec.fld <- c(dS=dS, dI=dI, dR=dR)
    return(list(vec.fld)) # ode() requires a list
  })
}
@
\item To tell \Rlogo that we want to solve this differential equation we need to tell it to integrate the equations above using the parameters we give it, from the initial conditions we specify. The chunk of code below takes the parameters, $\R_0$ and $\frac{1}{\gamma}$, and calculates the parameters $\beta$ and $\gamma$ and uses them to solve the ODE, starting from the initial conditions, \code{ic} that we give, using the time points \code{times}. We then add this solution to the current plot using the \code{lines} command.
<<Q3b2>>=
draw.soln <- function(ic=c(S=0.999,I=0.001,R=0), tmax=1, 
                      times=seq(0,tmax,length.out = 500), 
                      func, parms=c(R_0=2,gamma_inv=1), 
                      colour="blue", ... ) {
  # Solve ode from vector field using deSolve package and 
  # initial condition and parameters given
  with(as.list(parms),{
    gamma=1/gamma_inv
    beta=gamma*R_0
    soln <- ode(y=ic, times=times, func, 
                parms=c(beta=beta,gamma=gamma)) # Solve the ode 
    lines(times, soln[,"I"], 
          col=colour, ... ) # Add this line to our plot
    return(data.frame(time=times,y=soln[,"I"]))
  })
}
@
\item Finally we use these two functions to solve the differential equations with our parameters and initial conditions.
<<Q3b3,fig=TRUE,height=4,width=4>>=
tmax <- 10 # end time for numerical integration of the ODE
## draw box for plot:
plot(0,0,xlim=c(0,tmax),ylim=c(0,1),
     type="n",xlab="Time (t)",ylab="Prevalence (I)",las=1)
## initial conditions:
I0 <- 0.001
S0 <- 1 - I0
R0 <-  0
## Set parameter values
Rknot_vals <- 2.5
gamma_inv <- 1
# Solve ode for these parameters and initial conditions
p <- draw.soln(ic=c(S=S0,I=I0,R=R0), tmax=tmax,
          func=SIR.vector.field,
          parms=c(R_0=Rknot_vals,gamma_inv=gamma_inv,lwd=5)
)
@
 \end{itemize}
 \end{proof}
 }

\item \FitSIRc

  {\color{blue} \begin{proof}[Solution]
  Using the code written in part (b) we will make several calls to these functions to plot a series of curves with different $\R_0$ values.
<< Q3c, fig=TRUE, hieght=4,width=6,fig.show="hold",dev="tikz">>=
tmax <- 40 # end time for numerical integration of the ODE
## initial conditions:
I0 <- 0.001
S0 <- 1 - I0
R0 <-  0
gamma_inv=4
Rknot_vals <- c(1.2,1.5,1.8,2,3,4)
## draw box for plot:
plot(0,0,xlim=c(0,tmax),ylim=c(0,0.5),
     type="n",xlab="Time (t)",
     ylab="Prevalence (I)",las=1)
## draw solution for each value of Rknot:
for (i in 1:length(Rknot_vals)) {
  draw.soln(ic=c(S=S0,I=I0,R=R0), tmax=tmax,
            times=seq(0,tmax,length.out = 500),
            func=SIR.vector.field,
            parms=c(R_0=Rknot_vals[i],gamma_inv=gamma_inv),
            lwd=2, colour=rainbow(length(Rknot_vals)+1)[i] 
            # use a different line colour for each solution
            )
}
legend("topright",legend=Rknot_vals,
       col=rainbow(length(Rknot_vals)+1),lwd=2)
title(paste("SIR curves with varied","$R_0$","Values"))
@
  {\color{magenta}\dots beautifully clear text and plot(s) here \dots\ preceded by \Rlogo code if this is a \texttt{knitr} script}
  \end{proof}
  }
  
\item \FitSIRd

  {\color{blue} \begin{proof}[Solution]
  {\color{magenta}\dots beautifully clear text and plot(s) here \dots\ interspersed with \Rlogo code if this is a \texttt{knitr} script}
  \end{proof}
  }
 
\end{enumerate}

\section{Executive summary for the Public Health Agency}

\ExecSumm

  {\color{blue} \begin{proof}[Solution]
  {\color{magenta}\dots beautifully clear executive summary here, on its own page\dots}
  \end{proof}
  }

\bigskip

\centerline{\bf--- END OF ASSIGNMENT ---}

\bigskip
Compile time for this document:
\today\ @ \thistime

\end{document}
